### ISSUE TITLE
구매목록

### ISSUE THREAD

**Issue by Jungmo** [Ajou-masinda/Project_malhanda#3]
http://www.handmax.co.kr/shop/shopdetail.html?branduid=1073502&search=%25C0%25FD%25BF%25AC%25C0%25E5%25B0%25A9&sort=&xcode=001&mcode=006&scode=&GfDT=bm1%2BW10%3D

**Comment by clacis91** [comment]
10/13 구매목록 작성 완료

**Comment by clacis91** [comment]
구매완료
